name: kwirk_escape
description: a simple puzzle game for mobile and desktop browsers
version: 1.1.0
#homepage: https://www.example.com
author: Hummelsheim, Nicklas and Suer, Edward

environment:
  sdk: '>=2.3.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: '>=2.6.1 <3.0.0'
  pedantic: ^1.0.0
